TRADUCCIONES = {

    # ========================================================
    # ESPAÑOL → INGLÉS
    # ========================================================

    ("es", "en"): {

        # Expresiones religiosas
        "a dios": "goodbye",
        "adiós": "goodbye",
        "adios": "goodbye",
        "por Dios": "for God's sake",
        "por dios": "for God's sake",
        "Dios mío": "my God",
        "dios mío": "my God",
        "Dios mio": "my God",
        "dios mio": "my God",

        "gracias a Dios": "thank God",
        "gracias a dios": "thank God",
        "bendito sea Dios": "blessed be God",
        "bendito sea dios": "blessed be God",

        "Dios te bendiga": "God bless you",
        "dios te bendiga": "God bless you",
        "Dios los bendiga": "God bless you all",
        "dios los bendiga": "God bless you all",
        "que Dios te bendiga": "may God bless you",
        "que dios te bendiga": "may God bless you",
        "que Dios los bendiga": "may God bless you all",
        "que dios los bendiga": "may God bless you all",

        "si Dios quiere": "God willing",
        "si dios quiere": "God willing",
        "Dios mediante": "God willing",
        "dios mediante": "God willing",
        "con la ayuda de Dios": "with God's help",
        "con la ayuda de dios": "with God's help",

        "Dios sabe": "God knows",
        "dios sabe": "God knows",
        "solo Dios sabe": "only God knows",
        "solo dios sabe": "only God knows",
        "Dios lo sabe": "God knows",
        "dios lo sabe": "God knows",
        "Dios sabrá": "God will know",
        "dios sabra": "God will know",

        "Dios mío, ayúdame": "My God, help me",
        "dios mío ayúdame": "My God, help me",
        "Dios mio ayudame": "My God, help me",
        "dios mio ayudame": "My God, help me",
        "Dios mío, qué horror": "My God, how awful",
        "dios mío que horror": "My God, how awful",
        "Dios mío, qué pasa": "My God, what's happening",
        "dios mio que pasa": "My God, what's happening",

        "por el amor de Dios": "for God's sake",
        "por el amor de dios": "for God's sake",
        "por Dios, para": "for God's sake, stop",
        "por dios, para": "for God's sake, stop",

        "alabado sea Dios": "praise God",
        "alabado sea dios": "praise God",
        "gloria a Dios": "glory to God",
        "gloria a dios": "glory to God",
        "gloria al Señor": "glory to the Lord",
        "gloria al señor": "glory to the Lord",

        "Señor, ayúdame": "Lord, help me",
        "señor, ayúdame": "Lord, help me",
        "Señor ayúdame": "Lord, help me",
        "señor ayudame": "Lord, help me",
        "Dios, ayúdame": "God, help me",
        "dios ayudame": "God, help me",

        "que Dios me ayude": "may God help me",
        "que dios me ayude": "may God help me",
        "que Dios nos ayude": "may God help us",
        "que dios nos ayude": "may God help us",

        "Dios tenga piedad": "may God have mercy",
        "dios tenga piedad": "may God have mercy",
        "Dios tenga misericordia": "may God have mercy",
        "dios tenga misericordia": "may God have mercy",
        "ten piedad, Dios mío": "have mercy, my God",
        "ten piedad dios mío": "have mercy, my God",

        "por voluntad de Dios": "by God's will",
        "por voluntad de dios": "by God's will",
        "la voluntad de Dios": "the will of God",
        "la voluntad de dios": "the will of God",

        "palabra de Dios": "word of God",
        "palabra de dios": "word of God",
        "amor de Dios": "love of God",
        "amor de dios": "love of God",
        "gracia de Dios": "grace of God",
        "gracia de dios": "grace of God",

        "fe en Dios": "faith in God",
        "fe en dios": "faith in God",
        "creo en Dios": "I believe in God",
        "creo en dios": "I believe in God",
        "confío en Dios": "I trust in God",
        "confio en dios": "I trust in God",

        "Dios está conmigo": "God is with me",
        "dios esta conmigo": "God is with me",
        "Dios está contigo": "God is with you",
        "dios esta contigo": "God is with you",
        "Dios está con nosotros": "God is with us",
        "dios esta con nosotros": "God is with us",

        "que Dios te acompañe": "may God be with you",
        "que dios te acompañe": "may God be with you",
        "que Dios te proteja": "may God protect you",
        "que dios te proteja": "may God protect you",
        "que Dios nos proteja": "may God protect us",
        "que dios nos proteja": "may God protect us",

        "descansa en paz": "rest in peace",
        "que descanse en paz": "may he rest in peace",
        "en paz descanse": "may he rest in peace",

        "amén": "amen",
        "amen": "amen",
        "aleluya": "hallelujah",

        "Jesús": "Jesus",
        "jesus": "Jesus",
        "Jesucristo": "Jesus Christ",
        "jesucristo": "Jesus Christ",
        "Cristo": "Christ",
        "cristo": "Christ",
        "Señor": "Lord",
        "señor": "Lord",

        "en el nombre de Dios": "in the name of God",
        "en el nombre de dios": "in the name of God",
        "en el nombre de Jesús": "in the name of Jesus",
        "en el nombre de jesus": "in the name of Jesus",

        "gracias Señor": "thank you, Lord",
        "gracias señor": "thank you, Lord",
        "Señor ten piedad": "Lord have mercy",
        "señor ten piedad": "Lord have mercy",
        "que Dios te guarde": "may God keep you",
        "que dios te guarde": "may God keep you",

        "es una bendición": "it's a blessing",
        "es una bendicion": "it's a blessing",
        "qué bendición": "what a blessing",
        "que bendicion": "what a blessing",
        "milagro de Dios": "miracle of God",
        "milagro de dios": "miracle of God",
        "es un milagro": "it's a miracle",

        "Dios es bueno": "God is good",
        "dios es bueno": "God is good",
        "Dios es grande": "God is great",
        "dios es grande": "God is great",
        "Dios es amor": "God is love",
        "dios es amor": "God is love",

        "si Dios lo permite": "if God allows it",
        "si dios lo permite": "if God allows it",
        "que Dios quiera": "God willing",
        "con Dios": "with God",
        "junto a Dios": "with God",
        "cerca de Dios": "close to God",


        # Saludos y despedidas
        "buenos días": "good morning",
        "buen día": "good morning",
        "buen dia": "good day",
        "buenas tardes": "good afternoon",
        "buenas noches": "good night",
        "hasta luego": "see you later",
        "hasta pronto": "see you soon",
        "nos vemos": "see you",
        "qué tal": "how are you",
        "que tal": "how are you",
        "hola": "hello",
        "hola a todos": "hello everyone",
        "hola amigo": "hello friend",
        "hola amiga": "hello friend",
        "buenos dias": "good morning",
        "cómo estás": "how are you",
        "como estas": "like these",
        "cómo estás?": "how are you?",
        "como estas?": "how are you?",
        "cómo te va": "how are you doing",
        "como te va": "how are you doing",

        # Conversación
        "¿cómo estás?": "how are you?",
        "¿cómo estás": "how are you?",
        "mucho gusto": "nice to meet you",
        "encantado de conocerte": "nice to meet you",
        "encantada de conocerte": "nice to meet you",
        "qué haces?": "what are you doing?",
        "que haces?": "what are you doing?",
        "qué pasa": "what's going on",
        "que pasa": "what's going on",
        "qué pasa?": "what's going on?",
        "que pasa?": "what's going on?",
        "qué ocurre": "what's happening",
        "que ocurre": "what's happening",
        "qué quieres": "what do you want",
        "que quieres": "what do you want",
        "qué quieres?": "what do you want?",
        "qué necesitas": "what do you need",
        "que necesitas": "what do you need",
        "qué dices": "what are you saying",
        "que dices": "what are you saying",
        "qué estás haciendo": "what are you doing",
        "que estas haciendo": "what are you doing",
        "dónde estás": "where are you",
        "donde estas": "where are you",
        "dónde estás?": "where are you?",
        "donde estas?": "where are you?",
        "dónde vas": "where are you going",
        "donde vas": "where are you going",
        "dónde vives": "where do you live",
        "donde vives": "where do you live",

        # Agradecimientos
        "gracias": "thank you",
        "muchas gracias": "thank you very much",
        "de nada": "you're welcome",
        "no hay de qué": "you're welcome",
        "no hay de que": "you're welcome",
        "mil gracias": "thanks a lot",
        "gracias por todo": "thank you for everything",
        "gracias por tu ayuda": "thank you for your help",
        "gracias por ayudarme": "thank you for helping me",
        "no te preocupes": "don't worry",

        # Cortesía
        "por favor": "please",
        "perdón": "sorry",
        "perdon": "sorry",
        "lo siento": "I'm sorry",
        "disculpa": "excuse me",
        "disculpe": "excuse me",
        "con permiso": "excuse me",
        "claro que sí": "of course",
        "claro que si": "of course",
        "no pasa nada": "it's okay",
        "sin problema": "no problem",
        "ningún problema": "no problem",
        "ningun problema": "no problem",

        # Afirmación / negación
        "si": "yes",
        "no": "no",
        "por supuesto": "of course",
        "vale": "okay",
        "de acuerdo": "okay",
        "está bien": "it's okay",
        "esta bien": "it's okay",
        "tal vez": "maybe",
        "quizás": "maybe",
        "quizas": "maybe",
        "no lo sé": "I don't know",
        "no lo se": "I don't know",
        "no sé": "I don't know",
        "no se": "I don't know",
        "no entiendo": "I don't understand",
        "entiendo": "I understand",
        "ya entiendo": "I understand now",
        "lo entiendo": "I understand",
        "no puedo": "I can't",
        "puedo": "I can",
        "no quiero": "I don't want to",
        "quiero": "I want to",
        "no puedo hacerlo": "I can't do it",
        "puedo hacerlo": "I can do it",

        # Expresiones frecuentes
        "te quiero": "I love you",
        "te amo": "I love you",
        "te extraño": "I miss you",
        "te echo de menos": "I miss you",
        "tengo sueño": "I'm sleepy",
        "tengo miedo": "I'm scared",
        "¿qué pasa?": "what's going on?",
        "¿qué haces?": "what are you doing?",
        "que haces": "what are you doing?",
        "¿dónde estás?": "where are you?",
        "donde estás": "where you are",
        "¿qué quieres?": "what do you want?",
        "te quiero mucho": "I love you very much",
        "me gustas": "I like you",
        "me gusta": "I like it",
        "no me gusta": "I don't like it",
        "me encanta": "I love it",
        "odio esto": "I hate this",
        "estoy feliz": "I'm happy",
        "estoy triste": "I'm sad",
        "estoy cansado": "I'm tired",
        "estoy cansada": "I'm tired",
        "estoy aburrido": "I'm bored",
        "estoy aburrida": "I'm bored",
        "estoy ocupado": "I'm busy",
        "estoy ocupada": "I'm busy",
        "estoy preocupado": "I'm worried",
        "estoy preocupada": "I'm worried",
        "estoy enfadado": "I'm angry",
        "estoy enfadada": "I'm angry",

        # Tiempo
        "ahora": "now",
        "hoy": "today",
        "mañana": "tomorrow",
        "ayer": "yesterday",
        "esta mañana": "this morning",
        "esta tarde": "this afternoon",
        "esta noche": "tonight",
        "ahora mismo": "right now",
        "la semana que viene": "next week",
        "la semana pasada": "last week",
        "más tarde": "later",
        "mas tarde": "later",
        "después": "later",
        "despues": "later",
        "antes": "before",
        "pronto": "soon",

        # Personas
        "mi amigo": "my friend",
        "mi amiga": "my friend",
        "mi hermano": "my brother",
        "mi hermana": "my sister",
        "mi padre": "my father",
        "mi madre": "my mother",
        "mi mamá": "my mom",
        "mi mama": "my mom",
        "mi papá": "my dad",
        "mi papa": "my dad",
        "mi hijo": "my son",
        "mi hija": "my daughter",
        "mi novio": "my boyfriend",
        "mi novia": "my girlfriend",
        "mi marido": "my husband",
        "mi esposa": "my wife",

        # TRABAJO
        "estoy trabajando": "I'm working",
        "estoy en el trabajo": "I'm at work",
        "tengo trabajo": "I have work",
        "no tengo trabajo": "I don't have a job",
        "terminé de trabajar": "I finished work",
        "termine de trabajar": "I finished work",



        # Lugares / objetos comunes
        "mi casa": "my house",
        "mi coche": "my car",
        "mi teléfono": "my phone",
        "mi movil": "my phone",
        "mi móvil": "my phone",
        "mi habitación":"my room",
        "mi habitacion":"my room",
        "mi abitacion": "my room",
        "computadora": "computer",
        "aleatorio": "random",
        "teléfono móvil": "mobile phone",
        "telefono movil": "mobile phone",


        # DESPLAZAMIENTO
        "voy": "I'm going",
        "voy a casa": "I'm going home",
        "me voy a casa": "I'm going home",
        "voy al trabajo": "I'm going to work",
        "voy a trabajar": "I'm going to work",
        "voy a dormir": "I'm going to sleep",
        "me voy a dormir": "I'm going to bed",
        "voy a comer": "I'm going to eat",
        "voy a salir": "I'm going out",
        "estoy saliendo": "I'm leaving",
        "estoy de camino": "I'm on my way",
        "ya voy": "I'm coming",
        "ahora voy": "I'm coming now",
        "ya voy para allá": "I'm on my way",
        "ya voy para alla": "I'm on my way",
        "voy para casa": "I'm going home",
        "estoy llegando": "I'm arriving",
        "ya llegué": "I've arrived",
        "ya llegue": "I've arrived",



        # Frases frecuentes
        "te llamo luego": "I'll call you later",
        "hablamos luego": "talk to you later",
        "nos vemos mañana": "see you tomorrow",
        "hasta mañana": "see you tomorrow",
        "nos vemos luego": "see you later",
        "me voy": "I'm leaving",
        "ya me voy": "I'm leaving now",
        "me tengo que ir": "I have to go",
        "tengo que irme": "I have to go",
        "tengo que ir": "I have to go",
        "voy a irme": "I'm going to leave",
        "me marcho": "I'm leaving",
        "hasta la próxima": "see you next time",
        "hasta la proxima": "see you next time",
        "buen viaje": "have a good trip",
        "que tengas un buen día": "have a good day",
        "que tengas un buen dia": "have a good day",
        "tengo frío": "I'm cold",
        "tengo frio": "I'm cold",
        "tengo calor": "I'm hot",
        "tengo prisa": "I'm in a hurry",
        "tengo tiempo": "I have time",
        "no tengo tiempo": "I don't have time",
        "necesito dormir": "I need to sleep",
        "necesito comer": "I need to eat",
        "necesito irme": "I need to leave",
        "ayúdame": "help me",
        "ayudame": "help me",
        "necesito ayuda": "I need help",
        "ayuda": "help",
        "qué ha pasado": "what happened",
        "que ha pasado": "what happened",
        "no funciona": "it doesn't work",
        "funciona": "it works",
        "hay un problema": "there is a problem",
        "tenemos un problema": "we have a problem",
        "no funciona bien": "it doesn't work properly",
        "qué quieres decir": "what do you mean",
        "que quieres decir": "what do you mean",
        "qué significa": "what does it mean",
        "que significa": "what does it mean",
        "cómo se dice": "how do you say",
        "como se dice": "how do you say",
        "cómo se dice en inglés": "how do you say it in English",
        "como se dice en ingles": "how do you say it in English",
        "dame un momento": "give me a moment",
        "espera un momento": "wait a moment",
        "espera": "wait",
        "un momento": "one moment",
        "ven aquí": "come here",
        "ven aqui": "come here",
        "mira esto": "look at this",
        "escúchame": "listen to me",
        "escuchame": "listen to me",
        "mírame": "look at me",
        "mirame": "look at me",
        "déjame en paz": "leave me alone",
        "dejame en paz": "leave me alone",
        "ten cuidado": "be careful",
        "todo está bien": "everything is fine",
        "todo esta bien": "everything is fine",
        "está todo bien": "everything is okay",
        "esta todo bien": "everything is okay",
        "qué buena idea": "what a good idea",
        "que buena idea": "what a good idea",
        "no tengo ni idea": "I have no idea",
        "eso es verdad": "that's true",
        "es verdad": "it's true",
        "tienes razón": "you're right",
        "tienes razon": "you're right",
        "tienes toda la razón": "you're absolutely right",
        "tienes toda la razon": "you're absolutely right",
        "no tienes razón": "you're wrong",
        "no tienes razon": "you're wrong",
        "dónde está el hotel": "where is the hotel",
        "donde esta el hotel": "where is the hotel",
        "dónde está el aeropuerto": "where is the airport",
        "donde esta el aeropuerto": "where is the airport",
        "quiero ir al aeropuerto": "I want to go to the airport",
        "estoy perdido": "I'm lost",
        "estoy perdida": "I'm lost",
        "¿cuánto cuesta?": "how much does it cost?",
        "cuánto cuesta": "how much does it cost",
        "cuanto cuesta": "how much does it cost",

        # ====================================================
        # VOCABULARIO BÁSICO
        # ====================================================

        "esto": "this",
        "eso": "that",
        "aquello": "that",
        "aquí": "here",
        "aqui": "here",
        "ahí": "there",
        "ahi": "there",
        "allí": "there",
        "alli": "there",

        "hotel": "hotel",
        "aeropuerto": "airport",
        "trabajo": "work",
        "coche": "car",
        "teléfono": "phone",
        "telefono": "phone",
        "móvil": "phone",
        "movil": "phone",

        "madre": "mother",
        "mamá": "mom",
        "mama": "mom",
        "padre": "father",
        "papá": "dad",
        "papa": "dad",

        "amigo": "friend",
        "amiga": "friend",
        "hermano": "brother",
        "hermana": "sister",
        "hijo": "son",
        "hija": "daughter",

        "persona": "person",
        "personas": "people",
        "cosa": "thing",
        "cosas": "things",
        "noche": "night",

        # ====================================================
        # COLORES Y VARIANTES
        # ====================================================

        "color": "color",
        "colores": "colors",

        "blanco": "white",
        "blanca": "white",
        "negro": "black",
        "negra": "black",
        "rojo": "red",
        "roja": "red",
        "azul": "blue",
        "verde": "green",
        "amarillo": "yellow",
        "amarilla": "yellow",
        "naranja": "orange",
        "rosa": "pink",
        "rosado": "pink",
        "rosada": "pink",
        "morado": "purple",
        "morada": "purple",
        "violeta": "violet",
        "lila": "lilac",
        "gris": "gray",
        "marrón": "brown",
        "marron": "brown",
        "beige": "beige",
        "dorado": "golden",
        "dorada": "golden",
        "plateado": "silver",
        "plateada": "silver",

        # Tonos claros
        "azul claro": "light blue",
        "azul cielo": "sky blue",
        "celeste": "sky blue",
        "verde claro": "light green",
        "amarillo claro": "light yellow",
        "rosa claro": "light pink",
        "rosado claro": "light pink",
        "morado claro": "light purple",
        "lila claro": "light lilac",
        "gris claro": "light gray",
        "marrón claro": "light brown",
        "beige claro": "light beige",

        # Tonos oscuros
        "azul oscuro": "dark blue",
        "azul marino": "navy blue",
        "verde oscuro": "dark green",
        "rojo oscuro": "dark red",
        "rojo vino": "wine red",
        "amarillo oscuro": "dark yellow",
        "rosa oscuro": "dark pink",
        "morado oscuro": "dark purple",
        "gris oscuro": "dark gray",
        "marrón oscuro": "dark brown",

        # Tonos especiales
        "turquesa": "turquoise",
        "aguamarina": "aquamarine",
        "cian": "cyan",
        "magenta": "magenta",
        "fucsia": "fuchsia",
        "coral": "coral",
        "ocre": "ochre",
        "oliva": "olive",
        "verde oliva": "olive green",
        "verde lima": "lime green",
        "verde esmeralda": "emerald green",
        "azul eléctrico": "electric blue",
        "azul electrico": "electric blue",
        "azul turquesa": "turquoise blue",
        "rojo brillante": "bright red",
        "rojo intenso": "deep red",
        "negro brillante": "glossy black",
        "blanco puro": "pure white",
        "blanco roto": "off-white",
        "gris plata": "silver gray",
        "gris carbón": "charcoal gray",
        "gris carbon": "charcoal gray",

        # Intensidad de colores
        "muy claro": "very light",
        "muy oscuro": "very dark",
        "claro": "light",
        "oscuro": "dark",
        "brillante": "bright",
        "apagado": "dull",
        "intenso": "deep",
        "suave": "soft",

        # ====================================================
        # NÚMEROS Y CANTIDADES
        # ====================================================

        "número": "number",
        "numero": "number",
        "números": "numbers",
        "numeros": "numbers",

        # Números básicos
        "cero": "zero",
        "uno": "one",
        "una": "one",
        "dos": "two",
        "tres": "three",
        "cuatro": "four",
        "cinco": "five",
        "seis": "six",
        "siete": "seven",
        "ocho": "eight",
        "nueve": "nine",
        "diez": "ten",

        "once": "eleven",
        "doce": "twelve",
        "trece": "thirteen",
        "catorce": "fourteen",
        "quince": "fifteen",
        "dieciséis": "sixteen",
        "dieciseis": "sixteen",
        "diecisiete": "seventeen",
        "dieciocho": "eighteen",
        "diecinueve": "nineteen",
        "veinte": "twenty",

        "treinta": "thirty",
        "cuarenta": "forty",
        "cincuenta": "fifty",
        "sesenta": "sixty",
        "setenta": "seventy",
        "ochenta": "eighty",
        "noventa": "ninety",

        "cien": "one hundred",
        "ciento": "one hundred",
        "doscientos": "two hundred",
        "doscientas": "two hundred",
        "trescientos": "three hundred",
        "trescientas": "three hundred",
        "cuatrocientos": "four hundred",
        "cuatrocientas": "four hundred",
        "quinientos": "five hundred",
        "quinientas": "five hundred",
        "seiscientos": "six hundred",
        "seiscientas": "six hundred",
        "setecientos": "seven hundred",
        "setecientas": "seven hundred",
        "ochocientos": "eight hundred",
        "ochocientas": "eight hundred",
        "novecientos": "nine hundred",
        "novecientas": "nine hundred",

        "mil": "one thousand",
        "dos mil": "two thousand",
        "diez mil": "ten thousand",
        "cien mil": "one hundred thousand",
        "un millón": "one million",
        "un millon": "one million",
        "millón": "million",
        "millon": "million",
        "millones": "millions",

        # Decimales
        "coma": "point",
        "punto decimal": "decimal point",
        "medio": "half",
        "media": "half",
        "tercio": "third",
        "cuarto": "quarter",
        "cuartos": "quarters",

        # Cantidades
        "cantidad": "amount",
        "mucho": "a lot",
        "mucha": "a lot",
        "muchos": "many",
        "muchas": "many",
        "poco": "little",
        "poca": "little",
        "pocos": "few",
        "pocas": "few",
        "algo": "something",
        "nada": "nothing",
        "todo": "everything",
        "todos": "everyone",
        "cada": "each",
        "alguno": "some",
        "alguna": "some",
        "algunos": "some",
        "algunas": "some",
        "varios": "several",
        "varias": "several",
        "suficiente": "enough",
        "demasiado": "too much",
        "demasiados": "too many",

        # Comparaciones de cantidad
        "más": "more",
        "mas": "more",
        "menos": "less",
        "igual": "same",
        "diferente": "different",
        "primero": "first",
        "tercero": "third",
        "último": "last",
        "ultimo": "last",

        # Expresiones numéricas
        "uno más": "one more",
        "uno menos": "one less",
        "la mitad": "half",
        "el doble": "double",
        "el triple": "triple",
        "por ciento": "percent",
        "cien por cien": "one hundred percent",

        # ====================================================
        # DÍAS, MESES, ESTACIONES Y FECHAS
        # ====================================================

        "calendario": "calendar",
        "fecha": "date",
        "fechas": "dates",
        "día": "day",
        "dia": "day",
        "días": "days",
        "dias": "days",
        "semana": "week",
        "semanas": "weeks",
        "mes": "month",
        "meses": "months",
        "año": "year",
        "años": "years",

        # Días de la semana
        "lunes": "Monday",
        "martes": "Tuesday",
        "miércoles": "Wednesday",
        "miercoles": "Wednesday",
        "jueves": "Thursday",
        "viernes": "Friday",
        "sábado": "Saturday",
        "sabado": "Saturday",
        "domingo": "Sunday",

        "día laborable": "weekday",
        "dia laborable": "weekday",
        "día de trabajo": "working day",
        "dia de trabajo": "working day",
        "fin de semana": "weekend",
        "fines de semana": "weekends",
        "entre semana": "during the week",

        # Meses
        "enero": "January",
        "febrero": "February",
        "marzo": "March",
        "abril": "April",
        "mayo": "May",
        "junio": "June",
        "julio": "July",
        "agosto": "August",
        "septiembre": "September",
        "setiembre": "September",
        "octubre": "October",
        "noviembre": "November",
        "diciembre": "December",

        # Estaciones
        "primavera": "spring",
        "verano": "summer",
        "otoño": "autumn",
        "otono": "autumn",
        "invierno": "winter",
        "estación": "season",
        "estacion": "season",
        "estaciones": "seasons",

        # Fechas

        "manana": "tomorrow",
        "anteayer": "the day before yesterday",
        "pasado mañana": "the day after tomorrow",
        "pasado manana": "the day after tomorrow",
        "esta semana": "this week",
        "la próxima semana": "next week",
        "la proxima semana": "next week",
        "la semana anterior": "previous week",
        "el mes pasado": "last month",
        "el próximo mes": "next month",
        "el proximo mes": "next month",
        "el año pasado": "last year",
        "el año que viene": "next year",
        "el año próximo": "next year",

        "primera fecha": "first date",
        "última fecha": "last date",
        "ultima fecha": "last date",
        "cumpleaños": "birthday",
        "cumpleanos": "birthday",
        "día de cumpleaños": "birthday",

        # Tiempo y duración
        "hora": "hour",
        "horas": "hours",
        "minuto": "minute",
        "minutos": "minutes",
        "segundo": "second",
        "segundos": "seconds",
        "momento": "moment",
        "instante": "instant",
        "duración": "duration",
        "duracion": "duration",
        "tiempo": "time",
        "época": "period",
        "epoca": "period",
        "siglo": "century",

        "temprano": "early",
        "tarde": "late",
        "a tiempo": "on time",
        "a última hora": "at the last minute",
        "a ultima hora": "at the last minute",
        "desde": "from",
        "hasta": "until",
        "durante": "during",

        # ====================================================
        # TIEMPO ATMOSFÉRICO
        # ====================================================

        "clima": "weather",
        "tiempo atmosférico": "weather",
        "pronóstico del tiempo": "weather forecast",
        "pronostico del tiempo": "weather forecast",

        "hace sol": "it's sunny",
        "está soleado": "it's sunny",
        "esta soleado": "it's sunny",
        "está nublado": "it's cloudy",
        "esta nublado": "it's cloudy",
        "hay nubes": "there are clouds",
        "llueve": "it's raining",
        "está lloviendo": "it's raining",
        "esta lloviendo": "it's raining",
        "lluvia": "rain",
        "nieve": "snow",
        "nieva": "it's snowing",
        "viento": "wind",
        "hace viento": "it's windy",
        "tormenta": "storm",
        "tormenta eléctrica": "thunderstorm",
        "rayo": "lightning",
        "trueno": "thunder",
        "niebla": "fog",

        "calor": "heat",
        "frío": "cold",
        "frio": "cold",
        "temperatura": "temperature",
        "grado": "degree",
        "grados": "degrees",

        "hace calor": "it's hot",
        "hace frío": "it's cold",
        "hace frio": "it's cold",
        "hace fresco": "it's cool",
        "está congelando": "it's freezing",
        "esta congelando": "it's freezing",


        # ====================================================
        # ANIMALES, NATURALEZA Y PLANTAS
        # ====================================================

        # Animales generales
        "animal": "animal",
        "animales": "animals",
        "mascota": "pet",
        "mascotas": "pets",
        "salvaje": "wild",
        "doméstico": "domestic",
        "domestico": "domestic",

        # Mamíferos
        "perro": "dog",
        "perra": "female dog",
        "gato": "cat",
        "gata": "female cat",
        "caballo": "horse",
        "yegua": "mare",
        "vaca": "cow",
        "toro": "bull",
        "cerdo": "pig",
        "oveja": "sheep",
        "cabra": "goat",
        "conejo": "rabbit",
        "ratón": "mouse",
        "raton": "mouse",
        "rata": "rat",
        "león": "lion",
        "leon": "lion",
        "tigre": "tiger",
        "elefante": "elephant",
        "jirafa": "giraffe",
        "mono": "monkey",
        "oso": "bear",
        "lobo": "wolf",
        "zorro": "fox",
        "ciervo": "deer",
        "delfín": "dolphin",
        "delfin": "dolphin",
        "ballena": "whale",
        "murciélago": "bat",
        "murcielago": "bat",

        # Aves
        "pájaro": "bird",
        "pajaro": "bird",
        "ave": "bird",
        "águila": "eagle",
        "aguila": "eagle",
        "halcón": "falcon",
        "halcon": "falcon",
        "búho": "owl",
        "buho": "owl",
        "paloma": "dove",
        "cuervo": "crow",
        "gallina": "hen",
        "gallo": "rooster",
        "pato": "duck",
        "cisne": "swan",
        "pingüino": "penguin",
        "pinguino": "penguin",

        # Reptiles y anfibios
        "serpiente": "snake",
        "lagarto": "lizard",
        "tortuga": "turtle",
        "cocodrilo": "crocodile",
        "rana": "frog",
        "sapo": "toad",

        # Insectos
        "insecto": "insect",
        "insectos": "insects",
        "mariposa": "butterfly",
        "abeja": "bee",
        "mosca": "fly",
        "mosquito": "mosquito",
        "hormiga": "ant",
        "araña": "spider",
        "escarabajo": "beetle",

        # Animales marinos
        "pez": "fish",
        "peces": "fish",
        "tiburón": "shark",
        "tiburon": "shark",
        "pulpo": "octopus",
        "cangrejo": "crab",
        "estrella de mar": "starfish",
        "medusa": "jellyfish",

        # Partes de animales
        "ala": "wing",
        "alas": "wings",
        "cola": "tail",
        "pata": "leg",
        "patas": "legs",
        "garra": "claw",
        "piel": "skin",
        "pelo": "hair",
        "pluma": "feather",
        "plumas": "feathers",

        # Naturaleza
        "naturaleza": "nature",
        "mundo": "world",
        "planeta tierra": "earth",
        "planeta": "planet",
        "campo": "field",
        "bosque": "forest",
        "selva": "jungle",
        "montaña": "mountain",
        "montana": "mountain",
        "colina": "hill",
        "valle": "valley",
        "río": "river",
        "rio": "river",
        "lago": "lake",
        "mar": "sea",
        "océano": "ocean",
        "oceano": "ocean",
        "playa": "beach",
        "isla": "island",
        "desierto": "desert",
        "cueva": "cave",
        "cascada": "waterfall",

        # Plantas
        "planta": "plant",
        "plantas": "plants",
        "árbol": "tree",
        "arbol": "tree",
        "flor": "flower",
        "flores": "flowers",
        "hierba": "grass",
        "césped": "grass",
        "cesped": "grass",
        "hoja": "leaf",
        "hojas": "leaves",
        "rama": "branch",
        "raíz": "root",
        "raiz": "root",
        "semilla": "seed",
        "fruto": "fruit",

        # Elementos naturales
        "agua": "water",
        "fuego": "fire",
        "aire": "air",
        "tierra": "ground",
        "piedra": "stone",
        "roca": "rock",
        "arena": "sand",
        "barro": "mud",
        "hielo": "ice",
        "nube": "cloud",
        "cielo": "sky",
        "sol": "sun",
        "luna": "moon",
        "estrella": "star",

        # ====================================================
        # CUERPO HUMANO Y SALUD
        # ====================================================

        # Cuerpo general
        "cuerpo": "body",
        "cuerpos": "bodies",
        "humano": "human",
        "hueso": "bone",
        "huesos": "bones",
        "músculo": "muscle",
        "musculo": "muscle",
        "músculos": "muscles",
        "sangre": "blood",
        "corazón": "heart",
        "corazon": "heart",
        "cerebro": "brain",
        "mente": "mind",
        "pulmón": "lung",
        "pulmon": "lung",
        "pulmones": "lungs",
        "estómago": "stomach",
        "estomago": "stomach",
        "hígado": "liver",
        "higado": "liver",
        "riñón": "kidney",
        "rinon": "kidney",
        "intestino": "intestine",

        # Cabeza y cara
        "cabeza": "head",
        "cara": "face",
        "frente": "forehead",
        "ojo": "eye",
        "ojos": "eyes",
        "nariz": "nose",
        "boca": "mouth",
        "labio": "lip",
        "labios": "lips",
        "diente": "tooth",
        "dientes": "teeth",
        "lengua": "tongue",
        "oreja": "ear",
        "orejas": "ears",
        "barba": "beard",
        "bigote": "mustache",
        "cuello": "neck",

        # Brazos y manos
        "hombro": "shoulder",
        "hombros": "shoulders",
        "brazo": "arm",
        "brazos": "arms",
        "codo": "elbow",
        "muñeca": "wrist",
        "muneca": "wrist",
        "mano": "hand",
        "manos": "hands",
        "dedo": "finger",
        "dedos": "fingers",
        "uña": "nail",
        "unas": "nails",
        "pulgar": "thumb",

        # Piernas y pies
        "pierna": "leg",
        "piernas": "legs",
        "rodilla": "knee",
        "rodillas": "knees",
        "tobillo": "ankle",
        "pie": "foot",
        "pies": "feet",
        "dedo del pie": "toe",
        "talón": "heel",
        "talon": "heel",

        # Salud
        "salud": "health",
        "enfermedad": "illness",
        "enfermedades": "illnesses",
        "enfermo": "sick",
        "enferma": "sick",
        "sano": "healthy",
        "sana": "healthy",
        "médico": "doctor",
        "medico": "doctor",
        "doctora": "doctor",
        "enfermero": "nurse",
        "hospital": "hospital",
        "clínica": "clinic",
        "clinica": "clinic",
        "farmacia": "pharmacy",
        "medicina": "medicine",
        "medicamento": "medication",
        "pastilla": "pill",
        "pastillas": "pills",

        # Síntomas
        "dolor": "pain",
        "dolor de cabeza": "headache",
        "dolor de garganta": "sore throat",
        "fiebre": "fever",
        "tos": "cough",
        "resfriado": "cold",
        "gripe": "flu",
        "mareo": "dizziness",
        "náuseas": "nausea",
        "nauseas": "nausea",
        "vómito": "vomit",
        "vomito": "vomit",
        "herida": "wound",
        "corte": "cut",
        "quemadura": "burn",
        "infección": "infection",
        "infeccion": "infection",

        # Acciones relacionadas con salud
        "respirar": "to breathe",
        "respiración": "breathing",
        "respiracion": "breathing",
        "curar": "to heal",
        "sanar": "to heal",
        "descansar": "to rest",
        "recuperarse": "to recover",
        "tomar medicina": "take medicine",
        "ir al médico": "go to the doctor",
        "ir al medico": "go to the doctor",

        # Estados físicos
        "cansancio": "tiredness",
        "cansado": "tired",
        "cansada": "tired",
        "hambriento": "hungry",
        "sediento": "thirsty",
        "débil": "weak",
        "debil": "weak",
        "fuerte": "strong",
        "mareado": "dizzy",
        "mareada": "dizzy",


        # ====================================================
        # ROPA, ACCESORIOS Y CALZADO
        # ====================================================

        # Ropa general
        "ropa": "clothes",
        "prenda": "garment",
        "prendas": "garments",
        "vestimenta": "clothing",
        "talla": "size",
        "tallas": "sizes",
        "moda": "fashion",
        "estilo": "style",
        "marca": "brand",

        # Partes superiores
        "camisa": "shirt",
        "camiseta": "t-shirt",
        "camisetas": "t-shirts",
        "blusa": "blouse",
        "jersey": "sweater",
        "suéter": "sweater",
        "sudadera": "hoodie",
        "chaqueta": "jacket",
        "abrigo": "coat",
        "chaleco": "vest",
        "americana": "blazer",
        "corbata": "tie",
        "pajarita": "bow tie",

        # Partes inferiores
        "pantalón": "pants",
        "pantalon": "pants",
        "vaqueros": "jeans",
        "jean": "jeans",
        "falda": "skirt",
        "short": "shorts",
        "pantalones cortos": "shorts",
        "chándal": "tracksuit",
        "chandal": "tracksuit",
        "leggins": "leggings",

        # Vestidos
        "vestido": "dress",
        "traje": "suit",
        "esmoquin": "tuxedo",
        "uniforme": "uniform",
        "pijama": "pajamas",
        "bata": "robe",

        # Ropa interior
        "ropa interior": "underwear",
        "calzoncillo": "underwear",
        "braga": "panties",
        "sujetador": "bra",
        "calcetín": "sock",
        "calcetin": "sock",
        "calcetines": "socks",
        "medias": "stocking",

        # Calzado
        "zapato": "shoe",
        "zapatos": "shoes",
        "zapatilla": "sneaker",
        "zapatillas": "sneakers",
        "botas": "boots",
        "bota": "boot",
        "sandalia": "sandal",
        "chancla": "flip flop",
        "zueco": "clog",

        # Accesorios
        "gafas": "glasses",
        "gafas de sol": "sunglasses",
        "reloj": "watch",
        "anillo": "ring",
        "collar": "necklace",
        "pulsera": "bracelet",
        "pendiente": "earring",
        "pendientes": "earrings",
        "sombrero": "hat",
        "gorra": "cap",
        "bufanda": "scarf",
        "guantes": "gloves",
        "cinturón": "belt",
        "cinturon": "belt",
        "bolso": "handbag",
        "mochila": "backpack",
        "cartera": "wallet",
        "paraguas": "umbrella",

        # Materiales
        "algodón": "cotton",
        "algodon": "cotton",
        "lana": "wool",
        "seda": "silk",
        "cuero": "leather",
        "piel artificial": "synthetic leather",
        "plástico": "plastic",
        "plastico": "plastic",
        "metal": "metal",

        # Estados de la ropa
        "nuevo": "new",
        "nueva": "new",
        "viejo": "old",
        "vieja": "old",
        "limpio": "clean",
        "limpia": "clean",
        "sucio": "dirty",
        "sucia": "dirty",
        "roto": "broken",
        "rota": "broken",
        "cómodo": "comfortable",
        "comodo": "comfortable",
        "incómodo": "uncomfortable",
        "incomodo": "uncomfortable",

        # Comprar ropa
        "comprar ropa": "buy clothes",
        "probar": "try on",
        "probarse": "try on",
        "me queda bien": "it fits me well",
        "me queda mal": "it doesn't fit me",
        "es demasiado grande": "it's too big",
        "es demasiado pequeño": "it's too small",
        "es demasiado pequeno": "it's too small",
        "quiero otra talla": "I want another size",

        # ====================================================
        # CASA, HABITACIONES, MUEBLES Y HOGAR
        # ====================================================

        # Casa general
        "casa": "house",
        "hogar": "home",
        "vivienda": "home",
        "apartamento": "apartment",
        "piso": "apartment",
        "edificio": "building",
        "bloque": "block",
        "habitación": "room",
        "habitacion": "room",
        "habitaciones": "rooms",
        "puerta": "door",
        "ventana": "window",
        "pared": "wall",
        "techo": "ceiling",
        "suelo": "floor",
        "escalera": "stairs",
        "ascensor": "elevator",
        "garaje": "garage",
        "jardín": "garden",
        "jardin": "garden",
        "balcón": "balcony",
        "balcon": "balcony",
        "terraza": "terrace",

        # Habitaciones
        "salón": "living room",
        "salon": "living room",
        "sala": "living room",
        "comedor": "dining room",
        "cocina": "kitchen",
        "baño": "bathroom",
        "bano": "bathroom",
        "aseo": "toilet",
        "dormitorio": "bedroom",
        "habitación de matrimonio": "master bedroom",
        "habitacion de matrimonio": "master bedroom",
        "despacho": "office",
        "estudio": "study room",
        "trastero": "storage room",
        "lavandería": "laundry room",
        "lavanderia": "laundry room",

        # Muebles
        "mesa": "table",
        "silla": "chair",
        "sofá": "sofa",
        "sofa": "sofa",
        "sillón": "armchair",
        "sillon": "armchair",
        "cama": "bed",
        "armario": "wardrobe",
        "ropero": "closet",
        "estantería": "shelf",
        "estanteria": "shelf",
        "escritorio": "desk",
        "mesita": "small table",
        "cajón": "drawer",
        "cajon": "drawer",
        "espejo": "mirror",
        "alfombra": "carpet",
        "cortina": "curtain",
        "persiana": "blind",
        "lámpara": "lamp",
        "lampara": "lamp",
        "cuadro": "picture",
        "decoración": "decoration",
        "decoracion": "decoration",

        # Cocina
        "nevera": "fridge",
        "frigorífico": "fridge",
        "frigorifico": "fridge",
        "congelador": "freezer",
        "horno": "oven",
        "microondas": "microwave",
        "lavavajillas": "dishwasher",
        "fregadero": "sink",
        "grifo": "tap",
        "plato": "plate",
        "platos": "plates",
        "vaso": "glass",
        "vasos": "glasses",
        "taza": "cup",
        "cuchara": "spoon",
        "tenedor": "fork",
        "cuchillo": "knife",
        "olla": "pot",
        "sartén": "pan",
        "sarten": "pan",
        "botella": "bottle",
        "bol": "bowl",

        # Baño
        "ducha": "shower",
        "bañera": "bathtub",
        "banera": "bathtub",
        "lavabo": "sink",
        "inodoro": "toilet",
        "jabón": "soap",
        "jabon": "soap",
        "champú": "shampoo",
        "champu": "shampoo",
        "toalla": "towel",
        "papel higiénico": "toilet paper",
        "papel higienico": "toilet paper",

        # Electrodomésticos
        "televisión": "television",
        "television": "television",
        "tele": "TV",
        "ordenador": "computer",
        "portátil": "laptop",
        "portatil": "laptop",
        "impresora": "printer",
        "aspiradora": "vacuum cleaner",
        "lavadora": "washing machine",
        "secadora": "dryer",
        "calefacción": "heating",
        "calefaccion": "heating",
        "aire acondicionado": "air conditioning",
        "ventilador": "fan",

        # Objetos comunes
        "llave": "key",
        "llaves": "keys",
        "candado": "padlock",
        "enchufe": "plug",
        "cable": "cable",
        "cargador": "charger",
        "batería": "battery",
        "bateria": "battery",
        "libro": "book",
        "papel": "paper",
        "bolígrafo": "pen",
        "boligrafo": "pen",
        "lápiz": "pencil",
        "lapiz": "pencil",
        "caja": "box",
        "bolsa": "bag",

        # Estados de la casa
        "ordenado": "tidy",
        "desordenado": "messy",
        "abierto": "open",
        "cerrado": "closed",
        "lleno": "full",
        "vacío": "empty",
        "vacio": "empty",

        # ====================================================
        # COMIDA, BEBIDAS Y RESTAURANTE
        # ====================================================

        # Comida general
        "alimento": "food",
        "alimentos": "foods",
        "receta": "recipe",
        "ingrediente": "ingredient",
        "ingredientes": "ingredients",
        "cocinar": "to cook",
        "cocinero": "cook",
        "cocinera": "cook",
        "hambre": "hunger",
        "desayuno": "breakfast",
        "almuerzo": "lunch",
        "comida": "lunch",
        "cena": "dinner",
        "merienda": "snack",

        # Carnes
        "carne": "meat",
        "pollo": "chicken",
        "ternera": "beef",
        "cordero": "lamb",
        "jamón": "ham",
        "jamon": "ham",
        "salchicha": "sausage",
        "hamburguesa": "hamburger",
        "filete": "steak",
        "bacon": "bacon",

        # Pescado y marisco
        "pescado": "fish",
        "salmón": "salmon",
        "salmon": "salmon",
        "atún": "tuna",
        "atun": "tuna",
        "marisco": "seafood",
        "gamba": "shrimp",
        "gambas": "shrimp",
        "calamar": "squid",

        # Verduras
        "verdura": "vegetable",
        "verduras": "vegetables",
        "lechuga": "lettuce",
        "tomate": "tomato",
        "cebolla": "onion",
        "ajo": "garlic",
        "patata": "potato",
        "zanahoria": "carrot",
        "pepino": "cucumber",
        "pimiento": "pepper",
        "espinaca": "spinach",
        "brócoli": "broccoli",
        "brocoli": "broccoli",

        # Frutas
        "fruta": "fruit",
        "frutas": "fruits",
        "manzana": "apple",
        "plátano": "banana",
        "platano": "banana",
        "limón": "lemon",
        "limon": "lemon",
        "fresa": "strawberry",
        "uva": "grape",
        "sandía": "watermelon",
        "sandia": "watermelon",
        "melón": "melon",
        "melon": "melon",
        "pera": "pear",

        # Panadería y dulces
        "pan": "bread",
        "pastel": "cake",
        "tarta": "cake",
        "galleta": "cookie",
        "galletas": "cookies",
        "chocolate": "chocolate",
        "azúcar": "sugar",
        "azucar": "sugar",
        "sal": "salt",
        "miel": "honey",
        "mermelada": "jam",
        "harina": "flour",

        # Lácteos
        "leche": "milk",
        "queso": "cheese",
        "yogur": "yogurt",
        "mantequilla": "butter",
        "nata": "cream",
        "huevo": "egg",
        "huevos": "eggs",

        # Bebidas
        "bebida": "drink",
        "bebidas": "drinks",
        "café": "coffee",
        "cafe": "coffee",
        "té": "tea",
        "te": "tea",
        "zumo": "juice",
        "jugo": "juice",
        "refresco": "soft drink",
        "cerveza": "beer",
        "vino": "wine",
        "batido": "milkshake",

        # Restaurante
        "restaurante": "restaurant",
        "bar": "bar",
        "camarero": "waiter",
        "camarera": "waitress",
        "reserva": "reservation",
        "menú": "menu",
        "menu": "menu",
        "cuenta": "bill",
        "propina": "tip",
        "cliente": "customer",

        # Frases de comida
        "tengo hambre": "I'm hungry",
        "tengo sed": "I'm thirsty",
        "quiero comer": "I want to eat",
        "quiero beber": "I want to drink",
        "vamos a comer": "let's eat",
        "vamos a cenar": "let's have dinner",
        "está delicioso": "it's delicious",
        "esta delicioso": "it's delicious",
        "está muy bueno": "it's very good",
        "no me gusta la comida": "I don't like the food",
        "soy vegetariano": "I'm vegetarian",
        "soy vegetariana": "I'm vegetarian",
        "sin azúcar": "without sugar",
        "sin azucar": "without sugar",
        "sin sal": "without salt",
        "más agua": "more water",
        "mas agua": "more water",
        "la cuenta por favor": "the bill please",








    },

    # =================================================

    # ========================================================
    # INGLÉS → ESPAÑOL
    # ========================================================

    ("en", "es"): {

        # ====================================================
        # EXPRESIONES RELIGIOSAS
        # ====================================================

        "goodbye": "adiós",
        "bye": "adiós",
        "farewell": "adiós",
        "for God's sake, stop": "por Dios, para",
        "praise God": "alabado sea Dios",
        "glory to God": "gloria a Dios",
        "glory to the Lord": "gloria al Señor",
        "by God's will": "por voluntad de Dios",
        "the will of God": "la voluntad de Dios",
        "word of God": "palabra de Dios",
        "love of God": "amor de Dios",
        "grace of God": "gracia de Dios",
        "faith in God": "fe en Dios",
        "I believe in God": "creo en Dios",
        "I trust in God": "confío en Dios",
        "God is with me": "Dios está conmigo",
        "God is with you": "Dios está contigo",
        "God is with us": "Dios está con nosotros",
        "may God be with you": "que Dios te acompañe",
        "may God protect you": "que Dios te proteja",
        "may God protect us": "que Dios nos proteja",
        "may God keep you": "que Dios te guarde",
        "with God": "con Dios",
        "close to God": "cerca de Dios",

        "for God's sake": "por Dios",
        "for gods sake": "por Dios",
        "my God": "Dios mío",
        "my god": "Dios mío",

        "thank God": "gracias a Dios",
        "blessed be God": "bendito sea Dios",
        "God bless you": "Dios te bendiga",
        "God bless you all": "Dios los bendiga",
        "may God bless you": "que Dios te bendiga",
        "may God bless you all": "que Dios los bendiga",

        "God willing": "si Dios quiere",
        "if God allows it": "si Dios lo permite",
        "with God's help": "con la ayuda de Dios",

        "God knows": "Dios sabe",
        "only God knows": "solo Dios sabe",
        "God will know": "Dios sabrá",

        "My God, help me": "Dios mío, ayúdame",
        "my God, help me": "Dios mío, ayúdame",
        "My God, how awful": "Dios mío, qué horror",
        "my God, how awful": "Dios mío, qué horror",
        "My God, what's happening": "Dios mío, qué está pasando",
        "my God, what's happening": "Dios mío, qué está pasando",

        "Lord, help me": "Señor, ayúdame",
        "God, help me": "Dios, ayúdame",
        "may God help me": "que Dios me ayude",
        "may God help us": "que Dios nos ayude",
        "may God have mercy": "que Dios tenga piedad",
        "have mercy, my God": "ten piedad, Dios mío",

        "rest in peace": "descansa en paz",
        "may he rest in peace": "que descanse en paz",
        "may she rest in peace": "que descanse en paz",

        "amen": "amén",
        "hallelujah": "aleluya",

        "Jesus": "Jesús",
        "Jesus Christ": "Jesucristo",
        "Christ": "Cristo",
        "Lord": "Señor",

        "in the name of God": "en el nombre de Dios",
        "in the name of Jesus": "en el nombre de Jesús",

        "thank you, Lord": "gracias, Señor",
        "Lord have mercy": "Señor, ten piedad",

        "it's a blessing": "es una bendición",
        "what a blessing": "qué bendición",
        "miracle of God": "milagro de Dios",
        "it's a miracle": "es un milagro",

        "God is good": "Dios es bueno",
        "God is great": "Dios es grande",
        "God is love": "Dios es amor",

        # ====================================================
        # SALUDOS
        # ====================================================

        "hello": "hola",
        "hi": "hola",
        "hello everyone": "hola a todos",
        "hello friend": "hola amigo",
        "good morning": "buenos días",
        "good day": "buen día",
        "good afternoon": "buenas tardes",
        "good evening": "buenas tardes",
        "good night": "buenas noches",

        "how are you": "¿cómo estás?",
        "how are you?": "¿cómo estás?",
        "how are you doing": "¿cómo te va?",
        "how are you doing?": "¿cómo te va?",

        # ====================================================
        # DESPEDIDAS
        # ====================================================

        "see you": "nos vemos",
        "see you later": "hasta luego",
        "see you soon": "hasta pronto",
        "see you tomorrow": "nos vemos mañana",
        "see you next time": "hasta la próxima",
        "I'm leaving": "me voy",
        "I'm leaving now": "ya me voy",
        "I have to go": "me tengo que ir",
        "I need to leave": "necesito irme",
        "I'm going to leave": "voy a irme",
        "I'm going home": "me voy a casa",
        "I'm going out": "voy a salir",

        # ====================================================
        # AGRADECIMIENTOS
        # ====================================================

        "thank you": "gracias",
        "thanks": "gracias",
        "thank you very much": "muchas gracias",
        "thanks a lot": "mil gracias",
        "thank you for everything": "gracias por todo",
        "thank you for your help": "gracias por tu ayuda",
        "thank you for helping me": "gracias por ayudarme",
        "don't worry": "no te preocupes",

        # ====================================================
        # CORTESÍA
        # ====================================================

        "please": "por favor",
        "sorry": "lo siento",
        "excuse me": "disculpa",
        "yes": "sí",
        "no": "no",
        "okay": "vale",
        "it's okay": "está bien",
        "that's okay": "está bien",
        "no worries": "no te preocupes",

        # ====================================================
        # CONVERSACIÓN
        # ====================================================


        "what are you doing": "¿qué estás haciendo?",
        "what are you doing?": "¿qué estás haciendo?",
        "what's going on": "¿qué pasa?",
        "what's going on?": "¿qué pasa?",
        "what's happening": "¿qué ocurre?",
        "what's happening?": "¿qué ocurre?",
        "what are you saying?": "¿qué dices?",

        "what do you want": "¿qué quieres?",
        "what do you want?": "¿qué quieres?",
        "what do you need": "¿qué necesitas?",
        "what do you need?": "¿qué necesitas?",

        "what are you saying": "¿qué estás diciendo?",

        "where are you": "¿dónde estás?",
        "where are you?": "¿dónde estás?",
        "where are you going": "¿adónde vas?",
        "where are you going?": "¿adónde vas?",

        "where do you live": "¿dónde vives?",
        "where do you live?": "¿dónde vives?",

        "what do you mean": "¿qué quieres decir?",
        "what do you mean?": "¿qué quieres decir?",
        "what does it mean": "¿qué significa?",
        "what does it mean?": "¿qué significa?",

        # ====================================================
        # RESPUESTAS
        # ====================================================

        "maybe": "quizás",
        "I don't know": "no lo sé",
        "I don't understand": "no entiendo",
        "I understand": "entiendo",
        "I understand now": "ya entiendo",
        "I can": "puedo",
        "I can't": "no puedo",
        "I want to": "quiero",
        "I don't want to": "no quiero",
        "I can do it": "puedo hacerlo",
        "I can't do it": "no puedo hacerlo",
        "no problem": "sin problema",
        "you're welcome": "de nada",
        "of course": "claro",


        # ====================================================
        # SENTIMIENTOS
        # ====================================================

        "I love you": "te quiero",
        "I love you very much": "te quiero mucho",
        "I miss you": "te extraño",
        "I like you": "me gustas",
        "I like it": "me gusta",
        "I don't like it": "no me gusta",
        "I love it": "me encanta",
        "I hate this": "odio esto",
        "I'm happy": "estoy feliz",
        "I'm sad": "estoy triste",
        "I'm tired": "estoy cansado",
        "I'm bored": "estoy aburrido",
        "I'm busy": "estoy ocupado",
        "I'm worried": "estoy preocupado",
        "I'm scared": "tengo miedo",
        "I'm angry": "estoy enfadado",


        # ====================================================
        # NECESIDADES
        # ====================================================

        "I'm hungry": "tengo hambre",
        "I'm thirsty": "tengo sed",
        "I'm sleepy": "tengo sueño",
        "I'm cold": "tengo frío",
        "I'm hot": "tengo calor",
        "I'm in a hurry": "tengo prisa",
        "I have time": "tengo tiempo",
        "I don't have time": "no tengo tiempo",

        "I need help": "necesito ayuda",
        "I need to sleep": "necesito dormir",
        "I need to eat": "necesito comer",

        # ====================================================
        # TIEMPO
        # ====================================================

        "now": "ahora",
        "right now": "ahora mismo",
        "this morning": "esta mañana",
        "this afternoon": "esta tarde",
        "tonight": "esta noche",
        "last week": "la semana pasada",
        "later": "más tarde",
        "before": "antes",
        "soon": "pronto",

        # ====================================================
        # FAMILIA
        # ====================================================

        "my mother": "mi madre",
        "my mom": "mi mamá",
        "my father": "mi padre",
        "my dad": "mi papá",
        "my brother": "mi hermano",
        "my sister": "mi hermana",
        "my son": "mi hijo",
        "my daughter": "mi hija",
        "my friend": "mi amigo",
        "my boyfriend": "mi novio",
        "my girlfriend": "mi novia",
        "my husband": "mi marido",
        "my wife": "mi esposa",

        # ====================================================
        # CASA / OBJETOS
        # ====================================================

        "my house": "mi casa",
        "at home": "en casa",
        "I'm at home": "estoy en casa",
        "my room": "mi habitación",
        "my car": "mi coche",
        "my phone": "mi teléfono",
        "mobile phone": "teléfono móvil",
        "random": "aleatorio",

        # ====================================================
        # DESPLAZAMIENTO
        # ====================================================

        "I'm going": "voy",
        "I'm going to work": "voy a trabajar",
        "I'm going to sleep": "voy a dormir",
        "I'm going to bed": "me voy a dormir",
        "I'm going to eat": "voy a comer",
        "I'm on my way": "estoy de camino",
        "I'm coming": "ya voy",
        "I'm coming now": "ahora voy",
        "I'm arriving": "estoy llegando",
        "I've arrived": "ya llegué",

        # ====================================================
        # TRABAJO
        # ====================================================

        "I'm working": "estoy trabajando",
        "I'm at work": "estoy en el trabajo",
        "I have work": "tengo trabajo",
        "I don't have a job": "no tengo trabajo",
        "I finished work": "terminé de trabajar",

        # ====================================================
        # COMIDA
        # ====================================================

        "let's have breakfast": "vamos a desayunar",
        "what are we eating": "¿qué comemos?",
        "what are we eating?": "¿qué comemos?",

        # ====================================================
        # AYUDA / PROBLEMAS
        # ====================================================

        "help": "ayuda",
        "help me": "ayúdame",
        "what happened": "¿qué ha pasado?",
        "it doesn't work": "no funciona",
        "it works": "funciona",
        "there is a problem": "hay un problema",
        "we have a problem": "tenemos un problema",
        "it doesn't work properly": "no funciona bien",

        # ====================================================
        # FRASES FRECUENTES
        # ====================================================

        "give me a moment": "dame un momento",
        "wait a moment": "espera un momento",
        "wait": "espera",
        "one moment": "un momento",
        "come here": "ven aquí",
        "look at this": "mira esto",
        "listen to me": "escúchame",
        "look at me": "mírame",
        "leave me alone": "déjame en paz",
        "be careful": "ten cuidado",

        "everything is fine": "todo está bien",
        "everything is okay": "está todo bien",
        "what a good idea": "qué buena idea",
        "I have no idea": "no tengo ni idea",
        "that's true": "eso es verdad",
        "it's true": "es verdad",
        "you're right": "tienes razón",
        "you're absolutely right": "tienes toda la razón",
        "you're wrong": "estás equivocado",
        "have a good day": "que tengas un buen día",

        # ====================================================
        # LLAMADAS / COMUNICACIÓN
        # ====================================================

        "I'll call you later": "te llamo luego",
        "talk to you later": "hablamos luego",

        # ====================================================
        # VIAJES
        # ====================================================

        "have a good trip": "buen viaje",
        "where is the hotel": "¿dónde está el hotel?",
        "where is the airport": "¿dónde está el aeropuerto?",
        "I want to go to the airport": "quiero ir al aeropuerto",
        "I'm lost": "estoy perdido",
        "how much does it cost": "¿cuánto cuesta?",
        "how much does it cost?": "¿cuánto cuesta?",

        # ====================================================
        # VOCABULARIO BÁSICO
        # ====================================================

        "this": "esto",
        "that": "eso",
        "here": "aquí",
        "there": "allí",
        "hotel": "hotel",
        "airport": "aeropuerto",
        "work": "trabajo",
        "car": "coche",
        "phone": "teléfono",
        "mother": "madre",
        "mom": "mamá",
        "father": "padre",
        "dad": "papá",
        "friend": "amigo",
        "brother": "hermano",
        "sister": "hermana",
        "son": "hijo",
        "daughter": "hija",

        "person": "persona",
        "people": "personas",
        "thing": "cosa",
        "things": "cosas",

        "night": "noche",

        # ====================================================
        # COLORS AND VARIANTS
        # ====================================================

        "color": "color",
        "colors": "colores",

        "white": "blanco",
        "black": "negro",
        "red": "rojo",
        "blue": "azul",
        "green": "verde",
        "yellow": "amarillo",
        "orange": "naranja",
        "pink": "rosa",
        "purple": "morado",
        "violet": "violeta",
        "lilac": "lila",
        "gray": "gris",
        "grey": "gris",
        "brown": "marrón",
        "beige": "beige",
        "golden": "dorado",
        "silver": "plateado",

        # Light shades
        "light blue": "azul claro",
        "sky blue": "azul cielo",
        "light green": "verde claro",
        "light yellow": "amarillo claro",
        "light pink": "rosa claro",
        "light purple": "morado claro",
        "light gray": "gris claro",
        "light brown": "marrón claro",
        "light beige": "beige claro",

        # Dark shades
        "dark blue": "azul oscuro",
        "navy blue": "azul marino",
        "dark green": "verde oscuro",
        "dark red": "rojo oscuro",
        "wine red": "rojo vino",
        "dark yellow": "amarillo oscuro",
        "dark pink": "rosa oscuro",
        "dark purple": "morado oscuro",
        "dark gray": "gris oscuro",
        "dark brown": "marrón oscuro",

        # Special colors
        "turquoise": "turquesa",
        "aquamarine": "aguamarina",
        "cyan": "cian",
        "magenta": "magenta",
        "fuchsia": "fucsia",
        "coral": "coral",
        "ochre": "ocre",
        "olive": "oliva",
        "olive green": "verde oliva",
        "lime green": "verde lima",
        "emerald green": "verde esmeralda",
        "electric blue": "azul eléctrico",
        "turquoise blue": "azul turquesa",
        "bright red": "rojo brillante",
        "deep red": "rojo intenso",
        "glossy black": "negro brillante",
        "pure white": "blanco puro",
        "off-white": "blanco roto",
        "silver gray": "gris plata",
        "charcoal gray": "gris carbón",

        # Color intensity
        "very light": "muy claro",
        "very dark": "muy oscuro",
        "light": "claro",
        "dark": "oscuro",
        "bright": "brillante",
        "dull": "apagado",
        "deep": "intenso",
        "soft": "suave",

        # ====================================================
        # NUMBERS AND QUANTITIES
        # ====================================================

        "number": "número",
        "numbers": "números",

        # Basic numbers
        "zero": "cero",
        "one": "uno",
        "two": "dos",
        "three": "tres",
        "four": "cuatro",
        "five": "cinco",
        "six": "seis",
        "seven": "siete",
        "eight": "ocho",
        "nine": "nueve",
        "ten": "diez",

        "eleven": "once",
        "twelve": "doce",
        "thirteen": "trece",
        "fourteen": "catorce",
        "fifteen": "quince",
        "sixteen": "dieciséis",
        "seventeen": "diecisiete",
        "eighteen": "dieciocho",
        "nineteen": "diecinueve",
        "twenty": "veinte",

        "thirty": "treinta",
        "forty": "cuarenta",
        "fifty": "cincuenta",
        "sixty": "sesenta",
        "seventy": "setenta",
        "eighty": "ochenta",
        "ninety": "noventa",

        "one hundred": "cien",
        "two hundred": "doscientos",
        "three hundred": "trescientos",
        "four hundred": "cuatrocientos",
        "five hundred": "quinientos",
        "six hundred": "seiscientos",
        "seven hundred": "setecientos",
        "eight hundred": "ochocientos",
        "nine hundred": "novecientos",

        "one thousand": "mil",
        "two thousand": "dos mil",
        "ten thousand": "diez mil",
        "one hundred thousand": "cien mil",
        "one million": "un millón",
        "million": "millón",
        "millions": "millones",

        # Decimals and fractions
        "point": "coma",
        "decimal point": "punto decimal",
        "half": "mitad",
        "third": "tercio",
        "quarter": "cuarto",
        "quarters": "cuartos",

        # Quantities
        "amount": "cantidad",
        "a lot": "mucho",
        "many": "muchos",
        "little": "poco",
        "few": "pocos",
        "something": "algo",
        "nothing": "nada",
        "everything": "todo",
        "everyone": "todos",
        "each": "cada",
        "some": "alguno",
        "several": "varios",
        "enough": "suficiente",
        "too much": "demasiado",
        "too many": "demasiados",

        # Comparisons
        "more": "más",
        "less": "menos",
        "same": "igual",
        "different": "diferente",
        "first": "primero",
        "last": "último",

        # Number expressions
        "one more": "uno más",
        "one less": "uno menos",
        "double": "doble",
        "triple": "triple",
        "percent": "por ciento",
        "one hundred percent": "cien por cien",

        # ====================================================
        # DAYS, MONTHS, SEASONS AND DATES
        # ====================================================

        "calendar": "calendario",
        "date": "fecha",
        "dates": "fechas",
        "day": "día",
        "days": "días",
        "week": "semana",
        "weeks": "semanas",
        "month": "mes",
        "months": "meses",
        "year": "año",
        "years": "años",

        # Days
        "Monday": "lunes",
        "Tuesday": "martes",
        "Wednesday": "miércoles",
        "Thursday": "jueves",
        "Friday": "viernes",
        "Saturday": "sábado",
        "Sunday": "domingo",

        "weekday": "día laborable",
        "working day": "día de trabajo",
        "weekend": "fin de semana",
        "weekends": "fines de semana",

        # Months
        "January": "enero",
        "February": "febrero",
        "March": "marzo",
        "April": "abril",
        "May": "mayo",
        "June": "junio",
        "July": "julio",
        "August": "agosto",
        "September": "septiembre",
        "October": "octubre",
        "November": "noviembre",
        "December": "diciembre",

        # Seasons
        "spring": "primavera",
        "summer": "verano",
        "autumn": "otoño",
        "fall": "otoño",
        "winter": "invierno",
        "season": "estación",
        "seasons": "estaciones",

        # Dates
        "today": "hoy",
        "tomorrow": "mañana",
        "yesterday": "ayer",
        "the day before yesterday": "anteayer",
        "the day after tomorrow": "pasado mañana",
        "this week": "esta semana",
        "next week": "la próxima semana",
        "last month": "el mes pasado",
        "next month": "el próximo mes",
        "last year": "el año pasado",
        "next year": "el año que viene",

        "birthday": "cumpleaños",

        # Time
        "hour": "hora",
        "hours": "horas",
        "minute": "minuto",
        "minutes": "minutos",
        "second": "segundo",
        "seconds": "segundos",
        "moment": "momento",
        "instant": "instante",
        "duration": "duración",
        "time": "tiempo",
        "century": "siglo",

        "early": "temprano",
        "late": "tarde",
        "on time": "a tiempo",
        "during": "durante",

        # Weather
        "weather": "clima",
        "weather forecast": "pronóstico del tiempo",
        "it's sunny": "hace sol",
        "it's cloudy": "está nublado",
        "there are clouds": "hay nubes",
        "it's raining": "llueve",
        "rain": "lluvia",
        "snow": "nieve",
        "it's snowing": "nieva",
        "wind": "viento",
        "it's windy": "hace viento",
        "storm": "tormenta",
        "thunderstorm": "tormenta eléctrica",
        "lightning": "rayo",
        "thunder": "trueno",
        "fog": "niebla",

        "heat": "calor",
        "temperature": "temperatura",
        "degree": "grado",
        "degrees": "grados",

        "it's hot": "hace calor",
        "it's cold": "hace frío",
        "it's cool": "hace fresco",
        "it's freezing": "está congelando",


        # ====================================================
        # ANIMALS, NATURE AND PLANTS
        # ====================================================

        "animal": "animal",
        "animals": "animales",
        "pet": "mascota",
        "pets": "mascotas",
        "wild": "salvaje",
        "domestic": "doméstico",

        # Mammals
        "dog": "perro",
        "cat": "gato",
        "horse": "caballo",
        "mare": "yegua",
        "cow": "vaca",
        "bull": "toro",
        "pig": "cerdo",
        "sheep": "oveja",
        "goat": "cabra",
        "rabbit": "conejo",
        "mouse": "ratón",
        "rat": "rata",
        "lion": "león",
        "tiger": "tigre",
        "elephant": "elefante",
        "giraffe": "jirafa",
        "monkey": "mono",
        "bear": "oso",
        "wolf": "lobo",
        "fox": "zorro",
        "deer": "ciervo",
        "dolphin": "delfín",
        "whale": "ballena",
        "bat": "murciélago",

        # Birds
        "bird": "pájaro",
        "eagle": "águila",
        "falcon": "halcón",
        "owl": "búho",
        "dove": "paloma",
        "crow": "cuervo",
        "hen": "gallina",
        "rooster": "gallo",
        "duck": "pato",
        "swan": "cisne",
        "penguin": "pingüino",

        # Reptiles and amphibians
        "snake": "serpiente",
        "lizard": "lagarto",
        "turtle": "tortuga",
        "crocodile": "cocodrilo",
        "frog": "rana",
        "toad": "sapo",

        # Insects
        "insect": "insecto",
        "insects": "insectos",
        "butterfly": "mariposa",
        "bee": "abeja",
        "fly": "mosca",
        "mosquito": "mosquito",
        "ant": "hormiga",
        "spider": "araña",
        "beetle": "escarabajo",

        # Marine animals
        "fish": "pez",
        "shark": "tiburón",
        "octopus": "pulpo",
        "crab": "cangrejo",
        "starfish": "estrella de mar",
        "jellyfish": "medusa",

        # Nature
        "nature": "naturaleza",
        "world": "mundo",
        "earth": "tierra",
        "planet": "planeta",
        "field": "campo",
        "forest": "bosque",
        "jungle": "selva",
        "mountain": "montaña",
        "hill": "colina",
        "valley": "valle",
        "river": "río",
        "lake": "lago",
        "sea": "mar",
        "ocean": "océano",
        "beach": "playa",
        "island": "isla",
        "desert": "desierto",
        "cave": "cueva",
        "waterfall": "cascada",

        # Plants
        "plant": "planta",
        "plants": "plantas",
        "tree": "árbol",
        "flower": "flor",
        "flowers": "flores",
        "grass": "hierba",
        "leaf": "hoja",
        "leaves": "hojas",
        "branch": "rama",
        "root": "raíz",
        "seed": "semilla",
        "fruit": "fruta",

        # Natural elements
        "water": "agua",
        "fire": "fuego",
        "air": "aire",
        "ground": "tierra",
        "stone": "piedra",
        "rock": "roca",
        "sand": "arena",
        "mud": "barro",
        "ice": "hielo",
        "cloud": "nube",
        "sky": "cielo",
        "sun": "sol",
        "moon": "luna",
        "star": "estrella",

        # ====================================================
        # HUMAN BODY AND HEALTH
        # ====================================================

        # General body
        "body": "cuerpo",
        "bodies": "cuerpos",
        "human": "humano",
        "skin": "piel",
        "bone": "hueso",
        "bones": "huesos",
        "muscle": "músculo",
        "muscles": "músculos",
        "blood": "sangre",
        "heart": "corazón",
        "brain": "cerebro",
        "mind": "mente",
        "lung": "pulmón",
        "lungs": "pulmones",
        "stomach": "estómago",
        "liver": "hígado",
        "kidney": "riñón",
        "intestine": "intestino",

        # Head and face
        "head": "cabeza",
        "face": "cara",
        "forehead": "frente",
        "eye": "ojo",
        "eyes": "ojos",
        "nose": "nariz",
        "mouth": "boca",
        "lip": "labio",
        "lips": "labios",
        "tooth": "diente",
        "teeth": "dientes",
        "tongue": "lengua",
        "ear": "oreja",
        "ears": "orejas",
        "hair": "pelo",
        "beard": "barba",
        "mustache": "bigote",
        "neck": "cuello",

        # Arms and hands
        "shoulder": "hombro",
        "shoulders": "hombros",
        "arm": "brazo",
        "arms": "brazos",
        "elbow": "codo",
        "wrist": "muñeca",
        "hand": "mano",
        "hands": "manos",
        "finger": "dedo",
        "fingers": "dedos",
        "nail": "uña",
        "nails": "uñas",
        "thumb": "pulgar",

        # Legs and feet
        "leg": "pierna",
        "legs": "piernas",
        "knee": "rodilla",
        "knees": "rodillas",
        "ankle": "tobillo",
        "foot": "pie",
        "feet": "pies",
        "toe": "dedo del pie",
        "heel": "talón",

        # Health
        "health": "salud",
        "illness": "enfermedad",
        "illnesses": "enfermedades",
        "sick": "enfermo",
        "healthy": "sano",
        "doctor": "médico",
        "nurse": "enfermero",
        "hospital": "hospital",
        "clinic": "clínica",
        "pharmacy": "farmacia",
        "medicine": "medicina",
        "medication": "medicamento",
        "pill": "pastilla",
        "pills": "pastillas",

        # Symptoms
        "pain": "dolor",
        "headache": "dolor de cabeza",
        "sore throat": "dolor de garganta",
        "fever": "fiebre",
        "cough": "tos",
        "cold": "resfriado",
        "flu": "gripe",
        "dizziness": "mareo",
        "nausea": "náuseas",
        "vomit": "vómito",
        "wound": "herida",
        "cut": "corte",
        "burn": "quemadura",
        "infection": "infección",

        # Health actions
        "to breathe": "respirar",
        "breathing": "respiración",
        "to heal": "curar",
        "to rest": "descansar",
        "to recover": "recuperarse",
        "take medicine": "tomar medicina",
        "go to the doctor": "ir al médico",

        # Physical states
        "tiredness": "cansancio",
        "tired": "cansado",
        "hungry": "hambriento",
        "thirsty": "sediento",
        "weak": "débil",
        "strong": "fuerte",
        "dizzy": "mareado",

        # ====================================================
        # CLOTHES, ACCESSORIES AND FOOTWEAR
        # ====================================================

        # General clothing
        "clothes": "ropa",
        "garment": "prenda",
        "garments": "prendas",
        "clothing": "vestimenta",
        "size": "talla",
        "sizes": "tallas",
        "fashion": "moda",
        "style": "estilo",
        "brand": "marca",

        # Upper clothing
        "shirt": "camisa",
        "t-shirt": "camiseta",
        "t-shirts": "camisetas",
        "blouse": "blusa",
        "sweater": "jersey",
        "hoodie": "sudadera",
        "jacket": "chaqueta",
        "coat": "abrigo",
        "vest": "chaleco",
        "blazer": "americana",
        "tie": "corbata",
        "bow tie": "pajarita",

        # Lower clothing
        "pants": "pantalón",
        "jeans": "vaqueros",
        "skirt": "falda",
        "shorts": "pantalones cortos",
        "tracksuit": "chándal",
        "leggings": "leggins",

        # Dresses
        "dress": "vestido",
        "suit": "traje",
        "tuxedo": "esmoquin",
        "uniform": "uniforme",
        "pajamas": "pijama",
        "robe": "bata",

        # Underwear
        "underwear": "ropa interior",
        "panties": "braga",
        "bra": "sujetador",
        "sock": "calcetín",
        "socks": "calcetines",
        "stocking": "media",

        # Footwear
        "shoe": "zapato",
        "shoes": "zapatos",
        "sneaker": "zapatilla",
        "sneakers": "zapatillas",
        "boot": "bota",
        "boots": "botas",
        "sandal": "sandalia",
        "flip flop": "chancla",
        "clog": "zueco",

        # Accessories
        "glasses": "gafas",
        "sunglasses": "gafas de sol",
        "watch": "reloj",
        "ring": "anillo",
        "necklace": "collar",
        "bracelet": "pulsera",
        "earring": "pendiente",
        "earrings": "pendientes",
        "hat": "sombrero",
        "cap": "gorra",
        "scarf": "bufanda",
        "gloves": "guantes",
        "belt": "cinturón",
        "handbag": "bolso",
        "backpack": "mochila",
        "wallet": "cartera",
        "umbrella": "paraguas",

        # Materials
        "cotton": "algodón",
        "wool": "lana",
        "silk": "seda",
        "leather": "cuero",
        "synthetic leather": "piel artificial",
        "plastic": "plástico",
        "metal": "metal",

        # Clothing states
        "new": "nuevo",
        "old": "viejo",
        "clean": "limpio",
        "dirty": "sucio",
        "broken": "roto",
        "comfortable": "cómodo",
        "uncomfortable": "incómodo",

        # Buying clothes
        "buy clothes": "comprar ropa",
        "try on": "probarse",
        "it fits me well": "me queda bien",
        "it doesn't fit me": "me queda mal",
        "it's too big": "es demasiado grande",
        "it's too small": "es demasiado pequeño",
        "I want another size": "quiero otra talla",

        # ====================================================
        # HOME, ROOMS, FURNITURE AND HOUSEHOLD
        # ====================================================

        "house": "casa",
        "home": "hogar",
        "apartment": "apartamento",
        "building": "edificio",
        "room": "habitación",
        "door": "puerta",
        "window": "ventana",
        "wall": "pared",
        "ceiling": "techo",
        "floor": "suelo",
        "stairs": "escalera",
        "elevator": "ascensor",
        "garage": "garaje",
        "garden": "jardín",
        "balcony": "balcón",
        "terrace": "terraza",

        # Rooms
        "living room": "salón",
        "dining room": "comedor",
        "kitchen": "cocina",
        "bathroom": "baño",
        "toilet": "aseo",
        "bedroom": "dormitorio",
        "master bedroom": "habitación de matrimonio",
        "office": "despacho",
        "study room": "estudio",
        "storage room": "trastero",
        "laundry room": "lavandería",

        # Furniture
        "table": "mesa",
        "chair": "silla",
        "sofa": "sofá",
        "armchair": "sillón",
        "bed": "cama",
        "wardrobe": "armario",
        "closet": "ropero",
        "shelf": "estantería",
        "desk": "escritorio",
        "drawer": "cajón",
        "mirror": "espejo",
        "carpet": "alfombra",
        "curtain": "cortina",
        "blind": "persiana",
        "lamp": "lámpara",

        # Kitchen
        "fridge": "nevera",
        "freezer": "congelador",
        "oven": "horno",
        "microwave": "microondas",
        "dishwasher": "lavavajillas",
        "sink": "fregadero",
        "tap": "grifo",
        "plate": "plato",
        "glass": "vaso",
        "cup": "taza",
        "spoon": "cuchara",
        "fork": "tenedor",
        "knife": "cuchillo",
        "pot": "olla",
        "pan": "sartén",
        "bottle": "botella",
        "bowl": "bol",

        # Bathroom
        "shower": "ducha",
        "bathtub": "bañera",
        "soap": "jabón",
        "shampoo": "champú",
        "towel": "toalla",
        "toilet paper": "papel higiénico",

        # Appliances
        "television": "televisión",
        "TV": "tele",
        "computer": "ordenador",
        "laptop": "portátil",
        "printer": "impresora",
        "vacuum cleaner": "aspiradora",
        "washing machine": "lavadora",
        "dryer": "secadora",
        "heating": "calefacción",
        "air conditioning": "aire acondicionado",
        "fan": "ventilador",

        # Objects
        "key": "llave",
        "keys": "llaves",
        "charger": "cargador",
        "battery": "batería",
        "clock": "reloj",
        "book": "libro",
        "paper": "papel",
        "pen": "bolígrafo",
        "pencil": "lápiz",
        "box": "caja",
        "bag": "bolsa",

        # House states
        "tidy": "ordenado",
        "messy": "desordenado",
        "open": "abierto",
        "closed": "cerrado",
        "full": "lleno",
        "empty": "vacío",

        # ====================================================
        # FOOD, DRINKS AND RESTAURANT
        # ====================================================

        # General food
        "food": "comida",
        "foods": "alimentos",
        "dish": "plato",
        "dishes": "platos",
        "recipe": "receta",
        "ingredient": "ingrediente",
        "ingredients": "ingredientes",
        "to cook": "cocinar",
        "cooking": "cocina",
        "cook": "cocinero",
        "hunger": "hambre",
        "breakfast": "desayuno",
        "lunch": "almuerzo",
        "dinner": "cena",
        "snack": "merienda",

        # Meat
        "meat": "carne",
        "chicken": "pollo",
        "beef": "ternera",
        "pork": "cerdo",
        "lamb": "cordero",
        "ham": "jamón",
        "sausage": "salchicha",
        "hamburger": "hamburguesa",
        "steak": "filete",
        "bacon": "bacon",

        # Fish and seafood
        "salmon": "salmón",
        "tuna": "atún",
        "seafood": "marisco",
        "shrimp": "gamba",
        "squid": "calamar",

        # Vegetables
        "vegetable": "verdura",
        "vegetables": "verduras",
        "lettuce": "lechuga",
        "tomato": "tomate",
        "onion": "cebolla",
        "garlic": "ajo",
        "potato": "patata",
        "carrot": "zanahoria",
        "cucumber": "pepino",
        "pepper": "pimiento",
        "spinach": "espinaca",
        "broccoli": "brócoli",

        # Fruits
        "fruits": "frutas",
        "apple": "manzana",
        "banana": "plátano",
        "lemon": "limón",
        "strawberry": "fresa",
        "grape": "uva",
        "watermelon": "sandía",
        "melon": "melón",
        "pear": "pera",

        # Bakery and sweets
        "bread": "pan",
        "cake": "pastel",
        "cookie": "galleta",
        "cookies": "galletas",
        "chocolate": "chocolate",
        "sugar": "azúcar",
        "salt": "sal",
        "honey": "miel",
        "jam": "mermelada",
        "flour": "harina",

        # Dairy
        "milk": "leche",
        "cheese": "queso",
        "yogurt": "yogur",
        "butter": "mantequilla",
        "cream": "nata",
        "egg": "huevo",
        "eggs": "huevos",

        # Drinks
        "drink": "bebida",
        "drinks": "bebidas",
        "coffee": "café",
        "tea": "té",
        "juice": "zumo",
        "soft drink": "refresco",
        "beer": "cerveza",
        "wine": "vino",
        "milkshake": "batido",

        # Restaurant
        "restaurant": "restaurante",
        "bar": "bar",
        "waiter": "camarero",
        "waitress": "camarera",
        "reservation": "reserva",
        "menu": "menú",
        "bill": "cuenta",
        "tip": "propina",
        "customer": "cliente",

        # Food phrases
        "I want to eat": "quiero comer",
        "I want to drink": "quiero beber",
        "let's eat": "vamos a comer",
        "let's have dinner": "vamos a cenar",
        "it's delicious": "está delicioso",
        "it's very good": "está muy bueno",
        "I don't like the food": "no me gusta la comida",
        "I'm vegetarian": "soy vegetariano",
        "without sugar": "sin azúcar",
        "without salt": "sin sal",
        "more water": "más agua",
        "the bill please": "la cuenta por favor",

    },
}